export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_NONE = 'GET_CURRENT_USER_NONE';
export const SIGN_OUT = 'SIGN_OUT';
export const SUBMIT_SIGN_IN_SUCCESS = 'SUBMIT_SIGN_IN_SUCCESS';
export const SUBMIT_SIGN_IN_FAILURE = 'SUBMIT_SIGN_IN_FAILURE';

export const GET_BOOKS_BEGIN = 'GET_BOOKS_BEGIN';
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const SORT_BOOKS = 'SORT_BOOKS';

export const GET_MEMBERS_BEGIN = 'GET_MEMBERS_BEGIN';
export const GET_MEMBERS_FAILURE = 'GET_MEMBERS_FAILURE';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const SET_CURRENT_MEMBER = 'SET_CURRENT_MEMBER';

export const GET_RATINGS_BEGIN = 'GET_RATINGS_BEGIN';
export const GET_RATINGS_FAILURE = 'GET_RATINGS_FAILURE';
export const GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS';
