/* Init */
export const INIT_APP = 'INIT_APP';

/* Auth */
export const ADD_USER_BEGIN = 'ADD_USER_BEGIN';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const RESET_PASSWORD_BEGIN = 'RESET_PASSWORD_BEGIN';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const SET_CURRENT_USER_BEGIN = 'SET_CURRENT_USER_BEGIN';
export const SET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
export const SUBMIT_SIGN_IN_BEGIN = 'SUBMIT_SIGN_IN_BEGIN';
export const SUBMIT_SIGN_IN_SUCCESS = 'SUBMIT_SIGN_IN_SUCCESS';
export const SUBMIT_SIGN_IN_FAILURE = 'SUBMIT_SIGN_IN_FAILURE';

/* Books */
export const ADD_BOOK_BEGIN = 'ADD_BOOK_BEGIN';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const GET_BOOKS_BEGIN = 'GET_BOOKS_BEGIN';
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const UPDATE_BOOK_RATING_BEGIN = 'UPDATE_BOOK_RATING_BEGIN';
export const UPDATE_BOOK_RATING_FAILURE = 'UPDATE_BOOK_RATING_FAILURE';
export const UPDATE_BOOK_RATING_SUCCESS = 'UPDATE_BOOK_RATING_SUCCESS';
export const SORT_BOOKS = 'SORT_BOOKS';

/* members */
export const ADD_MEMBER_BEGIN = 'ADD_MEMBER_BEGIN';
export const ADD_MEMBER_FAILURE = 'ADD_MEMBER_FAILURE';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const GET_MEMBERS_BEGIN = 'GET_MEMBERS_BEGIN';
export const GET_MEMBERS_FAILURE = 'GET_MEMBERS_FAILURE';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const SET_CURRENT_MEMBER_BEGIN = 'SET_CURRENT_MEMBER_BEGIN';
export const SET_CURRENT_MEMBER_FAILURE = 'SET_CURRENT_MEMBER_FAILURE';
export const SET_CURRENT_MEMBER_SUCCESS = 'SET_CURRENT_MEMBER_SUCCESS';

/* ratings */
export const ADD_RATING_BEGIN = 'ADD_RATING_BEGIN';
export const ADD_RATING_FAILURE = 'ADD_RATING_FAILURE';
export const ADD_RATING_SUCCESS = 'ADD_RATING_SUCCESS';
export const GET_RATINGS_BEGIN = 'GET_RATINGS_BEGIN';
export const GET_RATINGS_FAILURE = 'GET_RATINGS_FAILURE';
export const GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS';
export const UPDATE_RATING_BEGIN = 'UPDATE_RATING_BEGIN';
export const UPDATE_RATING_FAILURE = 'UPDATE_RATING_FAILURE';
export const UPDATE_RATING_SUCCESS = 'UPDATE_RATING_SUCCESS';
